version: '3.8'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sapi
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - jenkins_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: nathanrgs/praticando-api
    environment:
      SPRING_PROFILES_ACTIVE: staging
      DB_HOST: database
    ports:
      - "8585:8585"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - jenkins_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8585/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db-volume:

networks:
  jenkins_network:
    external: true
